### ISSUE TITLE
version mismatch 

### ISSUE THREAD

**Issue by lucienhsu** [takase1121/lite-fallback-fonts#3]
lite xl version: 2.0.5 

How can i solve it ?

<img width="612" alt="Snipaste_2022-09-08_13-01-10" src="https://user-images.githubusercontent.com/9442479/189038320-d109f9c4-4197-4b6a-99fb-67fa5f15c311.png">

**Comment by takase1121** [comment]
I am not sure if this plugin will work with 2.0.5 (due to the inclusion of subpixel draw functions but you can fix this by adding:
```lua
-- mod-version:2
```
On top of the file.

This plugin was supposed to be deprecated once v2.1.0 comes out because it is very terrible, but that hasn't come out yet.

**Comment by takase1121** [comment]
Please upgrade to v2.1.0 for an actual solution.
